### ISSUE TITLE
Prerender hangs and does not generate page

### ISSUE THREAD

**Issue by steeply** [prerender/prerender#363] opened 2016-11-18 09:59 UTC
normal service
```
getting https://example.com/#!/page/1
getting https://example.com/#!/page/2
getting https://example.com/#!/page/3
got 200 in 6374ms for https://example.com/#!/page/1
got 200 in 7434ms for https://example.com/#!/page/2
got 200 in 8647ms for https://example.com/#!/page/3
```

Stuck and no answer:
```
getting https://example.com/#!/page/100
getting https://example.com/#!/page/102
getting https://example.com/#!/page/103
getting https://example.com/#!/page/104
......
getting https://example.com/#!/page/120
```
It helps only manual reset.

NUM_ITERATIONS and NUM_SOFT_ITERATIONS default

**Comment by thoop** [comment] 2016-11-18 22:20
Can you send the actual URL you are testing to support@prerender.io? That way we can look into this and see what's going on.

Thanks!

**Comment by imikiani** [comment] 2016-11-19 05:53
Dear thoop, 
I have this problem too.
I cloned the repository and finally I couldnot render google.com via localhost:3000/https://google.com.
After that I told my friend and he test it on his Mac but he could run the render server.
My OS is Linux Mint 17 Rafaela.

**Comment by thoop** [comment] 2016-11-19 16:06
Did you run into any errors with `npm install`? Are you seeing a console output like this when starting your server?
```
2016-11-19T16:06:02.739Z starting worker thread #0
2016-11-19T16:06:02.937Z starting phantom...
2016-11-19T16:06:02.945Z Server running on port 1341
2016-11-19T16:06:04.139Z started phantom
```

Notice the `starting...` and finally the `started` saying that phantom was started correctly. Are you seeing that phantom is started fully there?

**Comment by steeply** [comment] 2016-11-21 04:49
No installation errors
The server starts successfully.
Periodically displays a log:
```
2016-11-21T04:44:43.094186380Z app[web.1]: 2016-11-21T04:44:43.094Z got 200 in 6339ms for getting https://example.com/#!/page/3212234
2016-11-21T04:44:43.163630151Z app[web.1]: 2016-11-21T04:44:43.163Z phantomjs terminated
2016-11-21T04:44:43.164736051Z app[web.1]: 2016-11-21T04:44:43.164Z starting phantom...
2016-11-21T04:44:43.286564409Z app[web.1]: 2016-11-21T04:44:43.286Z started phantom
```

After a while phantom stops responding

**Comment by steeply** [comment] 2016-11-21 04:50
I'm sorry, accidentally closed

**Comment by thoop** [comment] 2016-11-21 14:50
How much CPU/RAM does the server have that you are running Prerender on?

**Comment by steeply** [comment] 2016-11-21 15:02
allowed to use 1gb ram

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   6732     0 ?        Ssl  Nov18   0:00 /start web
herokui+     8  0.0  1.5 913132 16252 ?        Sl   Nov18   0:05 node server.js
herokui+   154  23.7  47.2 1233976 45028 ?       Sl   Nov18  13:27 /app/.heroku/node/bin/node /app/server.js
herokui+ 18755 17.3 26.0 2058676 265052 ?      Sl   14:59   0:06 /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1.2 --config=/tmp/f-1161021-154-1pdwdn3 /app/node_modules/phridge/lib/phantom/start.js /tmp/f-1161021-154-1pdwdn3
```

**Comment by imikiani** [comment] 2016-11-21 15:37
Sorry I was wrong.
Thank you I can now see ` started`. I installed phantom js by  going to node_modules/phantomjs-prebuilt ( `cd node_modules/phantomjs-prebuilt` ) and ran  `node install`

**Comment by steeply** [comment] 2016-11-21 16:48
Again managed to capture the error, the complete log for the last 5 minutes

```
2016-11-21T16:38:49.299166649Z app[web.1]: 2016-11-21T16:38:49.299Z got 200 in 7645ms for https://example.com/#!/page/822170
2016-11-21T16:38:51.224176417Z app[web.1]: 2016-11-21T16:38:51.224Z got 200 in 6607ms for https://example.com/#!/page/4984966
2016-11-21T16:38:52.644451865Z app[web.1]: 2016-11-21T16:38:52.644Z got 200 in 5603ms for https://example.com/#!/page/3641649
2016-11-21T16:38:53.517228284Z app[web.1]: 2016-11-21T16:38:53.517Z got 200 in 6926ms for https://example.com/#!/page/1905435
2016-11-21T16:38:54.834692616Z app[web.1]: 2016-11-21T16:38:54.834Z getting https://example.com/#!/page/495919
2016-11-21T16:38:59.127394807Z app[web.1]: 2016-11-21T16:38:59.127Z getting https://example.com/#!/page/2076361
2016-11-21T16:39:01.206568682Z app[web.1]: 2016-11-21T16:39:01.206Z getting https://example.com/#!/page/3414628
2016-11-21T16:39:01.878618526Z app[web.1]: 2016-11-21T16:39:01.878Z got 200 in 7044ms for https://example.com/#!/page/495919
2016-11-21T16:39:03.064928112Z app[web.1]: 2016-11-21T16:39:03.064Z getting https://example.com/#!/page/2832112
2016-11-21T16:39:04.256999784Z app[web.1]: 2016-11-21T16:39:04.256Z getting https://example.com/#!/page/4468695
2016-11-21T16:39:09.881326559Z app[web.1]: 2016-11-21T16:39:09.881Z got 200 in 8675ms for https://example.com/#!/page/3414628
2016-11-21T16:39:11.148228136Z app[web.1]: 2016-11-21T16:39:11.148Z got 200 in 5429ms for https://example.com/#!/page/5194780
2016-11-21T16:39:11.237628545Z app[web.1]: 2016-11-21T16:39:11.237Z phantomjs terminated
2016-11-21T16:39:11.238334968Z app[web.1]: 2016-11-21T16:39:11.238Z starting phantom...
2016-11-21T16:39:11.493919167Z app[web.1]: 2016-11-21T16:39:11.493Z started phantom
2016-11-21T16:39:13.917423553Z app[web.1]: 2016-11-21T16:39:13.917Z getting https://example.com/#!/page/4085145
2016-11-21T16:39:39.365272487Z app[web.1]: 2016-11-21T16:39:39.365Z getting https://example.com/#!/page/154266
2016-11-21T16:39:39.642680022Z app[web.1]: 2016-11-21T16:39:39.642Z getting https://example.com/#!/page/1325685
2016-11-21T16:39:39.955998306Z app[web.1]: 2016-11-21T16:39:39.955Z getting https://example.com/#!/page/1435028
2016-11-21T16:39:40.905197656Z app[web.1]: 2016-11-21T16:39:40.905Z got 200 in 1540ms for https://example.com/#!/page/154266
2016-11-21T16:39:41.167043969Z app[web.1]: 2016-11-21T16:39:41.166Z got 304 in 1211ms for https://example.com/#!/page/1435028
2016-11-21T16:39:44.469108043Z app[web.1]: 2016-11-21T16:39:44.468Z got 200 in 5323ms for https://example.com/#!/page/4163649
2016-11-21T16:39:44.716902657Z app[web.1]: 2016-11-21T16:39:44.716Z got 200 in 5074ms for https://example.com/#!/page/1325685
2016-11-21T16:39:50.634470002Z app[web.1]: 2016-11-21T16:39:50.634Z getting https://example.com/#!/page/630477
2016-11-21T16:39:53.070659717Z app[web.1]: 2016-11-21T16:39:53.070Z getting https://example.com/#!/page/1805776
2016-11-21T16:39:53.543563410Z app[web.1]: 2016-11-21T16:39:53.543Z getting https://example.com/#!/page/2283602
2016-11-21T16:39:53.656874495Z app[web.1]: 2016-11-21T16:39:53.656Z getting https://example.com/#!/page/3006561
2016-11-21T16:39:53.757992547Z app[web.1]: 2016-11-21T16:39:53.757Z getting https://example.com/#!/page/4459597
2016-11-21T16:39:53.902994283Z app[web.1]: 2016-11-21T16:39:53.902Z getting https://example.com/#!/page/3331117
2016-11-21T16:39:55.244660273Z app[web.1]: 2016-11-21T16:39:55.244Z got 200 in 1487ms for https://example.com/#!/page/4459597
2016-11-21T16:40:08.572902454Z app[web.1]: 2016-11-21T16:40:08.572Z getting https://example.com/#!/page/4975502
2016-11-21T16:40:15.675166331Z app[web.1]: 2016-11-21T16:40:15.675Z getting https://example.com/#!/page/630477
2016-11-21T16:40:18.156280157Z app[web.1]: 2016-11-21T16:40:18.155Z getting https://example.com/#!/page/1805776
2016-11-21T16:40:30.846183961Z app[web.1]: 2016-11-21T16:40:30.846Z getting https://example.com/#!/page/5133064
2016-11-21T16:40:30.887006720Z app[web.1]: 2016-11-21T16:40:30.886Z getting https://example.com/#!/page/5120246
2016-11-21T16:40:31.136401837Z app[web.1]: 2016-11-21T16:40:31.136Z getting https://example.com/#!/page/3978824
2016-11-21T16:40:33.636439436Z app[web.1]: 2016-11-21T16:40:33.636Z getting https://example.com/#!/page/4975502
2016-11-21T16:40:40.769818726Z app[web.1]: 2016-11-21T16:40:40.769Z getting https://example.com/#!/page/630477
2016-11-21T16:40:43.250470305Z app[web.1]: 2016-11-21T16:40:43.250Z getting https://example.com/#!/page/1805776
2016-11-21T16:40:50.649089312Z app[web.1]: 2016-11-21T16:40:50.648Z getting https://example.com/#!/page/630477
2016-11-21T16:40:53.077942555Z app[web.1]: 2016-11-21T16:40:53.077Z getting https://example.com/#!/page/1805776
2016-11-21T16:40:53.548872892Z app[web.1]: 2016-11-21T16:40:53.548Z getting https://example.com/#!/page/2283602
2016-11-21T16:40:53.663384553Z app[web.1]: 2016-11-21T16:40:53.663Z getting https://example.com/#!/page/3006561
2016-11-21T16:40:53.907204518Z app[web.1]: 2016-11-21T16:40:53.907Z getting https://example.com/#!/page/3331117
2016-11-21T16:40:58.732046432Z app[web.1]: 2016-11-21T16:40:58.731Z getting https://example.com/#!/page/4975502
2016-11-21T16:41:05.887554076Z app[web.1]: 2016-11-21T16:41:05.887Z getting https://example.com/#!/page/630477
2016-11-21T16:41:08.272550810Z app[web.1]: 2016-11-21T16:41:08.272Z getting https://example.com/#!/page/697693
2016-11-21T16:41:08.277083166Z app[web.1]: 2016-11-21T16:41:08.276Z getting https://example.com/#!/page/4595727
2016-11-21T16:41:08.284243640Z app[web.1]: 2016-11-21T16:41:08.284Z getting https://example.com/#!/page/4565259
2016-11-21T16:41:08.343981801Z app[web.1]: 2016-11-21T16:41:08.343Z getting https://example.com/#!/page/1805776
2016-11-21T16:41:08.581458470Z app[web.1]: 2016-11-21T16:41:08.581Z getting https://example.com/#!/page/4975502
2016-11-21T16:41:15.687030417Z app[web.1]: 2016-11-21T16:41:15.686Z getting https://example.com/#!/page/630477
2016-11-21T16:41:18.158613348Z app[web.1]: 2016-11-21T16:41:18.158Z getting https://example.com/#!/page/1805776
2016-11-21T16:41:23.804810358Z app[web.1]: 2016-11-21T16:41:23.804Z getting https://example.com/#!/page/4975502
```

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   6732    48 ?        Ssl  Nov18   0:00 /start web
herokui+     8  0.0  0.8 914156  8560 ?        Sl   Nov18   0:06 node server.js
herokui+   154  0.3  4.4 1236448 44804 ?       Sl   Nov18  15:17 /app/.heroku/node/bin/node /app/server.js
herokui+ 22334 10.2 35.5 2158488 361052 ?      Sl   16:39   0:09 /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1.2 --config=/tmp/f-1161021-154-6xpaq0 /app/node_modules/phridge/lib/phantom/start.js /tmp/f-1161021-154-6xpaq0
```

**Comment by thoop** [comment] 2016-11-21 17:22
Are you on the latest version of Prerender (4.3.1)? Everything looks fine from the logs you sent so I don't know why it would stop serving pages. Can you try setting NUM_SOFT_ITERATIONS to 5?

**Comment by steeply** [comment] 2016-11-21 19:27
yes, latest version.
Tomorrow I will try to change NUM_SOFT_ITERATIONS

**Comment by steeply** [comment] 2016-11-22 06:09
NUM_SOFT_ITERATIONS = 10 and NUM_SOFT_ITERATIONS = 5
It did not help =(
result is the same
```
2016-11-22T06:03:58.092355201Z app[web.1]: 2016-11-22T06:03:58.092Z got 200 in 5622ms for https://example.com/#!/page/2105298
2016-11-22T06:03:58.247402093Z app[web.1]: 2016-11-22T06:03:58.247Z got 200 in 6635ms for https://example.com/#!/page/2285848
2016-11-22T06:03:58.920961651Z app[web.1]: 2016-11-22T06:03:58.920Z got 200 in 6439ms for https://example.com/#!/page/5108468
2016-11-22T06:04:00.060276809Z app[web.1]: 2016-11-22T06:04:00.060Z got 200 in 6536ms for https://example.com/#!/page/4611509
2016-11-22T06:04:00.175612125Z app[web.1]: 2016-11-22T06:04:00.175Z got 200 in 5796ms for https://example.com/#!/page/4280391
2016-11-22T06:04:00.491566304Z app[web.1]: 2016-11-22T06:04:00.491Z got 200 in 4824ms for https://example.com/#!/page/1451207
2016-11-22T06:04:00.527541713Z app[web.1]: 2016-11-22T06:04:00.527Z got 200 in 5429ms for https://example.com/#!/page/3720651
2016-11-22T06:04:00.574324279Z app[web.1]: 2016-11-22T06:04:00.574Z phantomjs terminated
2016-11-22T06:04:00.575135892Z app[web.1]: 2016-11-22T06:04:00.575Z starting phantom...
2016-11-22T06:04:00.694687910Z app[web.1]: 2016-11-22T06:04:00.694Z started phantom
2016-11-22T06:04:00.810210908Z app[web.1]: 2016-11-22T06:04:00.810Z getting https://example.com/#!/page/719707
2016-11-22T06:04:08.728447948Z app[web.1]: 2016-11-22T06:04:08.728Z got 200 in 7919ms for https://example.com/#!/page/719707
2016-11-22T06:04:09.791163224Z app[web.1]: 2016-11-22T06:04:09.790Z getting https://example.com/#!/page/4347921
2016-11-22T06:04:10.099257266Z app[web.1]: 2016-11-22T06:04:10.099Z getting https://example.com/#!/page/5213095
2016-11-22T06:04:10.702329222Z app[web.1]: 2016-11-22T06:04:10.702Z getting https://example.com/#!/page/4214295
2016-11-22T06:04:11.859133697Z app[web.1]: 2016-11-22T06:04:11.859Z getting https://example.com/#!/page/286008
2016-11-22T06:04:12.045037993Z app[web.1]: 2016-11-22T06:04:12.044Z getting https://example.com/#!/page/5229167
2016-11-22T06:04:12.391178468Z app[web.1]: 2016-11-22T06:04:12.391Z getting https://example.com/#!/page/4599446
2016-11-22T06:04:12.640997246Z app[web.1]: 2016-11-22T06:04:12.640Z getting https://example.com/#!/page/3359227
2016-11-22T06:04:14.058523161Z app[web.1]: 2016-11-22T06:04:14.058Z got 200 in 3959ms for https://example.com/#!/page/5213095
2016-11-22T06:04:15.853630939Z app[web.1]: 2016-11-22T06:04:15.853Z got 200 in 3995ms for https://example.com/#!/page/286008
2016-11-22T06:04:16.552940117Z app[web.1]: 2016-11-22T06:04:16.552Z got 200 in 5850ms for https://example.com/#!/page/4214295
2016-11-22T06:04:16.964529539Z app[web.1]: 2016-11-22T06:04:16.964Z got 200 in 4920ms for https://example.com/#!/page/5229167
2016-11-22T06:04:17.157530285Z app[web.1]: 2016-11-22T06:04:17.157Z got 200 in 7367ms for https://example.com/#!/page/4347921
2016-11-22T06:04:18.452881557Z app[web.1]: 2016-11-22T06:04:18.452Z got 200 in 5812ms for https://example.com/#!/page/3359227
2016-11-22T06:04:20.103636745Z app[web.1]: 2016-11-22T06:04:20.103Z got 200 in 7712ms for https://example.com/#!/page/4599446
2016-11-22T06:04:20.136501581Z app[web.1]: 2016-11-22T06:04:20.136Z phantomjs terminated
2016-11-22T06:04:20.137112062Z app[web.1]: 2016-11-22T06:04:20.137Z starting phantom...
2016-11-22T06:04:20.237668907Z app[web.1]: 2016-11-22T06:04:20.237Z started phantom
2016-11-22T06:04:20.529310447Z app[web.1]: 2016-11-22T06:04:20.529Z getting https://example.com/#!/page/986473
2016-11-22T06:04:27.107921172Z app[web.1]: 2016-11-22T06:04:27.107Z getting https://example.com/#!/page/3363977
2016-11-22T06:04:27.722928600Z app[web.1]: 2016-11-22T06:04:27.722Z getting https://example.com/#!/page/5077855
2016-11-22T06:04:28.305001183Z app[web.1]: 2016-11-22T06:04:28.304Z got 200 in 7775ms for https://example.com/#!/page/986473
2016-11-22T06:04:28.908532337Z app[web.1]: 2016-11-22T06:04:28.908Z getting https://example.com/#!/page/3547857
2016-11-22T06:04:28.939612103Z app[web.1]: 2016-11-22T06:04:28.939Z getting https://example.com/#!/page/4513221
2016-11-22T06:04:28.967264558Z app[web.1]: 2016-11-22T06:04:28.967Z getting https://example.com/#!/page/1826335
2016-11-22T06:04:30.162285003Z app[web.1]: 2016-11-22T06:04:30.161Z got 200 in 1222ms for https://example.com/#!/page/4513221
2016-11-22T06:04:30.183226439Z app[web.1]: 2016-11-22T06:04:30.183Z getting https://example.com/#!/page/1843927
2016-11-22T06:04:30.389096621Z app[web.1]: 2016-11-22T06:04:30.388Z got 200 in 1480ms for https://example.com/#!/page/3547857
2016-11-22T06:04:32.121779802Z app[web.1]: 2016-11-22T06:04:32.121Z getting https://example.com/#!/page/2908991
2016-11-22T06:04:40.429386391Z app[web.1]: 2016-11-22T06:04:40.429Z getting https://example.com/#!/page/3972218
2016-11-22T06:04:41.922494034Z app[web.1]: 2016-11-22T06:04:41.922Z getting https://example.com/#!/page/5202338
2016-11-22T06:04:41.935239621Z app[web.1]: 2016-11-22T06:04:41.935Z getting https://example.com/#!/page/1338030
2016-11-22T06:04:52.196419399Z app[web.1]: 2016-11-22T06:04:52.196Z getting https://example.com/#!/page/3363977
2016-11-22T06:04:52.794501459Z app[web.1]: 2016-11-22T06:04:52.794Z getting https://example.com/#!/page/5077855
2016-11-22T06:04:54.050496432Z app[web.1]: 2016-11-22T06:04:54.050Z getting https://example.com/#!/page/1826335
2016-11-22T06:04:55.269988384Z app[web.1]: 2016-11-22T06:04:55.267Z getting https://example.com/#!/page/1843927
2016-11-22T06:04:57.230558258Z app[web.1]: 2016-11-22T06:04:57.230Z getting https://example.com/#!/page/2908991
2016-11-22T06:05:05.583130054Z app[web.1]: 2016-11-22T06:05:05.582Z getting https://example.com/#!/page/3972218
2016-11-22T06:05:07.006319680Z app[web.1]: 2016-11-22T06:05:07.006Z getting https://example.com/#!/page/5202338
2016-11-22T06:05:07.025377975Z app[web.1]: 2016-11-22T06:05:07.025Z getting https://example.com/#!/page/1338030
2016-11-22T06:05:17.283860752Z app[web.1]: 2016-11-22T06:05:17.283Z getting https://example.com/#!/page/3363977
2016-11-22T06:05:17.878122011Z app[web.1]: 2016-11-22T06:05:17.877Z getting https://example.com/#!/page/5077855
2016-11-22T06:05:19.139710536Z app[web.1]: 2016-11-22T06:05:19.139Z getting https://example.com/#!/page/1826335
2016-11-22T06:05:20.362804285Z app[web.1]: 2016-11-22T06:05:20.362Z getting https://example.com/#!/page/1843927
2016-11-22T06:05:22.292087376Z app[web.1]: 2016-11-22T06:05:22.291Z getting https://example.com/#!/page/2908991
2016-11-22T06:05:27.119973900Z app[web.1]: 2016-11-22T06:05:27.119Z getting https://example.com/#!/page/3363977

```

**Comment by steeply** [comment] 2016-11-22 07:12
Tried to run on the local machine. Configuration: RAM 16GB, CPU 8 cores.
Start 8 working Phantom

Sent 20 requests at the same time.
After 5 minutes, all phantom die.
Prepender tried to kill them "kill the power phantomjs", but he fell down with errors. And a log fell various a mess of errors and a promise from the other modules.

It turns out, the amount of flow as does not affect the success of the phantom

**Comment by thoop** [comment] 2016-11-28 18:57
We haven't run into these issues at all. I wonder if it's your code is somehow causing issues with PhantomJS? Can you post the errors from force killing phantomjs? Sounds like PhantomJS might have crashed without alerting the child process, which would explain why those requests wouldn't finish.

**Comment by steeply** [comment] 2016-11-29 03:27
```
2016-11-29T03:21:41.040Z got 504 in 46960ms for http://localhost:5000/#!/goods/110270
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at /Applications/MAMP/htdocs/prerender/lib/server.js:526:13
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:54:28)
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:61:13)
    at Object.beforeSend (/Applications/MAMP/htdocs/prerender/lib/plugins/removeScriptTags.js:14:9)
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:59:20)
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:61:13)
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:61:13)
    at next (/Applications/MAMP/htdocs/prerender/lib/server.js:61:13)
    at Object.server._pluginEvent (/Applications/MAMP/htdocs/prerender/lib/server.js:66:5)

2016-11-29T03:21:41.405Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:21:41.406Z got 504 in 55247ms for http://localhost:5000/#!/goods/110338
2016-11-29T03:21:41.590Z phantomjs terminated
2016-11-29T03:21:41.590Z starting phantom...
(node:33044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot communicate with PhantomJS process: Unknown reason
(node:33044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot communicate with PhantomJS process: Unknown reason
(node:33044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Cannot communicate with PhantomJS process: Unknown reason
(node:33045) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 47): Error: Cannot communicate with PhantomJS process: Unknown reason
2016-11-29T03:22:14.223Z started phantom
2016-11-29T03:22:25.061Z Experiencing infinite javascript loop. Killing phantomjs...
2016-11-29T03:22:25.063Z got 504 in 98793ms for http://localhost:5000/#!/goods/109119
2016-11-29T03:22:25.115Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:22:25.117Z got 504 in 98955ms for http://localhost:5000/#!/goods/109240
2016-11-29T03:22:25.231Z Experiencing infinite javascript loop. Killing phantomjs...
2016-11-29T03:22:25.233Z got 504 in 99050ms for http://localhost:5000/#!/goods/110251
2016-11-29T03:22:25.249Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:22:25.253Z got 504 in 99066ms for http://localhost:5000/#!/goods/109423
2016-11-29T03:22:25.292Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:22:25.294Z got 504 in 98793ms for http://localhost:5000/#!/goods/109289
2016-11-29T03:22:25.376Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:22:25.377Z got 504 in 99187ms for http://localhost:5000/#!/goods/109925
2016-11-29T03:22:25.500Z PhantomJS restarted in the middle of this request. Aborting...
2016-11-29T03:22:25.501Z got 504 in 99342ms for http://localhost:5000/#!/goods/109771
unable to dispose PhantomJS. Forcing kill...
2016-11-29T03:22:35.063Z phantomjs terminated
2016-11-29T03:22:35.063Z starting phantom...
Error: Cannot communicate with PhantomJS process: Unknown reason
    at Phantom._afterExit (/Applications/MAMP/htdocs/prerender/node_modules/phridge/lib/Phantom.js:348:17)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```


The entire log is very large, so the attached file
[scratch.txt](https://github.com/prerender/prerender/files/618045/scratch.txt)

**Comment by thoop** [comment] 2016-11-29 16:27
Yeah it definitely looks like your PhantomJS is having issues and our prerender process can't talk to it. Can you send me an example of one of your URLs so I can look into it more? Feel free to email me at todd@prerender.io if you want to keep your URL private.

**Comment by dzydzany** [comment] 2017-02-01 13:07
Just to confirm that we are having the same issue... Thanks!

**Comment by thoop** [comment] 2017-02-02 17:02
Can you provide any info to help us look into this? We haven't been able to reproduce it.

**Comment by johanbrook** [comment] 2017-02-20 13:38
I get this for our Meteor app (client side rendered), where we wanna do an external redirect to an `http://..` URL, but set correct `Location` and status code headers on the servers for spiders.

Our code is:

```js
const externalRedirect = (url) => ({
  triggersEnter: [() => {
    RouterHelpers.setStatus(301);
    RouterHelpers.setHeader(`Location: ${url}`);
  }],
  action: () => {
    window.location = url;
  }
});

route('/toproute/subroute',
    externalRedirect('http://external-url.com'));
```

The `triggersEnter` is a thing in our Meteor router (FlowRouter), which .. yeah, triggers on route enter. The `action` prop is the main body of the route, where you usually render a template.

The `setStatus` and `setHeader` functions sets proper meta tag attributes in the client side rendered HTML.

I've tried removing the `setStatus` and `setHeader` calls, moving them to `action`, but no change. I think it has something to do with the `window.location = url`, since when I remove that call, I get proper headers and status code on the server (with `curl`), but no client side redirect when visiting through the browser.

Do I need to delay

**Full server log trace**

```
$ curl -i http://localhost:3000/toproute/subroute?_escaped_fragment_=
HTTP/1.1 504 Gateway Timeout
x-content-type-options: nosniff
access-control-allow-origin: *
content-type: text/html;charset=UTF-8
vary: Accept-Encoding
date: Mon, 20 Feb 2017 13:34:14 GMT
connection: keep-alive
transfer-encoding: chunked
```

```
2017-02-20T13:34:14.477Z getting http://localhost:3000/toproute/subroute
2017-02-20T13:34:16.346Z got 504 in 1869ms for http://localhost:3000/toproute/subroute
2017-02-20T13:34:16.381Z unable to set header: x-content-type-options
2017-02-20T13:34:16.382Z unable to set header: content-security-policy
2017-02-20T13:34:16.382Z unable to set header: access-control-allow-origin
2017-02-20T13:34:16.382Z unable to set header: content-type
2017-02-20T13:34:16.382Z unable to set header: vary
2017-02-20T13:34:16.382Z unable to set header: content-encoding
2017-02-20T13:34:16.382Z unable to set header: date
2017-02-20T13:34:16.382Z unable to set header: connection
2017-02-20T13:34:16.382Z unable to set header: transfer-encoding
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at /Users/Johan/Projects/Code/lookback/prerender/lib/server.js:537:13
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:54:28)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at Object.module.exports.beforeSend (/Users/Johan/Projects/Code/lookback/prerender/lib/plugins/removeScriptTags.js:14:9)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:59:20)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at Object.server._pluginEvent (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:66:5)
    at Object.server._send (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:521:10)
2017-02-20T13:34:16.400Z unable to set header: x-content-type-options
2017-02-20T13:34:16.401Z unable to set header: content-security-policy
2017-02-20T13:34:16.401Z unable to set header: access-control-allow-origin
2017-02-20T13:34:16.401Z unable to set header: content-type
2017-02-20T13:34:16.401Z unable to set header: vary
2017-02-20T13:34:16.401Z unable to set header: content-encoding
2017-02-20T13:34:16.401Z unable to set header: date
2017-02-20T13:34:16.401Z unable to set header: connection
2017-02-20T13:34:16.404Z unable to set header: transfer-encoding
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at /Users/Johan/Projects/Code/lookback/prerender/lib/server.js:537:13
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:54:28)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at Object.module.exports.beforeSend (/Users/Johan/Projects/Code/lookback/prerender/lib/plugins/removeScriptTags.js:14:9)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:59:20)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at next (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:61:13)
    at Object.server._pluginEvent (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:66:5)
    at Object.server._send (/Users/Johan/Projects/Code/lookback/prerender/lib/server.js:521:10)
```

**Comment by thoop** [comment] 2017-02-20 15:20
The problem with `window.location = url;` would be that Meteor would redraw the page and might get rid of those meta tags (which means the Prerender server wouldn't see them so it wouldn't send back a 301).

I'm not sure why you are seeing a 504 and those header issues in your console. Do you have a public URL that you could send us so we could test that out on our end and see what's going on? support@prerender.io

**Comment by johanbrook** [comment] 2017-02-20 15:54
Gotcha. I'll deploy my stuff to a testing server in order to try to repro this. Will get back to you with more.

**Comment by thoop** [comment] 2017-02-20 19:05
Thanks! Going to close this issue since it's becoming a dumping ground for issues. Please create new issues for any Prerender rendering problems. Thanks everyone.

**Closed by thoop** 2017-02-20 19:05 UTC
