### ISSUE TITLE
doctype appended as string to document content

### ISSUE THREAD

**Issue by alexstanbury** [prerender/prerender#563] opened 2019-01-04 13:00 UTC
We've noticed an issue where the start of pre-rendered output string is of the following format:

`html<html lang="en" `

This is causing Facebook's scraper to not scrape properly, which makes sense as it's not valid html.

Looking through the source code, I notice in chrome.js the following lines (536-545):

```
}).then((response) => {

			let doctype = '';
			if (response && response.result && response.result.description) {
				doctype = response.result.description;
			}

			tab.prerender.content = doctype + tab.prerender.content;
			clearTimeout(parseTimeout);
			resolve();
```

Can you explain why the doctype is being appended like this as a string? How are we supposed to consume the `content` output of the prerender object?

Thanks

**Comment by thoop** [comment] 2019-01-04 17:46
Can you give an example of a URL where that is happening? Feel free to email that to me at todd@prerender.io if you want to keep it private.

When I run a local Prerender server and run:
```
curl -v http://localhost:1337/https://prerender.io/
```
I'm seeing a response starting with:
```
<!DOCTYPE html><html ng-app="prerender.io" class="ng-scope"><head>
```
So it's meant to add that doctype at the beginning there.

**Comment by alexstanbury** [comment] 2019-01-11 14:56
Thanks for the reply, I managed to narrow it down and eventually worked out it was Chrome Canary that was causing the issue. I had the following:

`chromeLocation: 'C:/Users/myusername/AppData/Local/Google/Chrome SxS/Application/chrome.exe'`

Once I removed that and let it use normal chrome the problem went away...Seems slightly slower now but at least it works properly!

**Comment by thoop** [comment] 2019-01-11 19:12
Great! Thanks. We will keep an eye on this.

**Comment by csims** [comment] 2019-02-04 22:32
I've noticed this issue using Prerender with the stable version of Chrome since updating to 72.0.3626.81 (MacOS and Debian) last week. For now, I'm working around it with a custom plugin to modify `req.prerender.content` on pageLoaded, but just wanted to give a heads up that this appears to no longer be just a Chrome Canary issue. Unfortunately, I don't have an externally accessible example url available at the moment.

Thanks!

**Comment by psloh** [comment] 2019-02-05 23:12
I just noticed this issue appear as well, on an Ubuntu 18.04 LTS system with current Node modules. It appears that document.doctype.description is now returning simply "html" instead of "<!DOCTYPE html>" in valid HTML documents. I put in a workaround in my lib/browsers/chrome.js file. Could you please test against the most current Google Chrome and most current Node modules pulled down by "npm install" to see if you also have this behavior? Thank you so much!

**Comment by thoop** [comment] 2019-02-07 05:47
I can confirm this as well with Chrome 72. Looks like we were depending on the default string value of the doctype object and that has changed. I'm about to push a backwards compatible fix that actually parses the correct doctype from the doctype object instead of relying on the correct string to be sent back.

**Comment by thoop** [comment] 2019-02-07 05:59
This should now be fixed in Prerender v5.5.1.

Thanks so much for reporting this and please let me know if you see an issues after upgrading!

**Comment by csims** [comment] 2019-03-18 19:04
I meant to post back here, but confirming that I'm no longer seeing this issue on my end with Chrome 72 after upgrading to Prerender 5.5.1. Thanks!

**Comment by thoop** [comment] 2019-03-28 02:16
Great, thanks!

**Closed by thoop** 2019-03-28 02:16 UTC
